version: "3.9"

services:
  app:
    build: .
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-change-me}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-0}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      UV_PROJECT_ENVIRONMENT: /app/.venv
    depends_on:
      - redis
    volumes:
      - ./static:/app/static:ro

  worker:
    build: .
    command: ["uv", "run", "arq", "app.worker.WorkerSettings"]
    restart: unless-stopped
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN:-change-me}
      TELEGRAM_CHAT_ID: ${TELEGRAM_CHAT_ID:-0}
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_DB: "0"
      UV_PROJECT_ENVIRONMENT: /app/.venv
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--appendonly", "no"]
